### ISSUE TITLE
會使拍羅馬字

### ISSUE THREAD

**Issue by a8568730** [i3thuan5/rime-taigi#3]

**Comment by a8568730** [comment]
看會著，毋過無法度選。
```
 translator:
    dictionary: taigi
    preedit_format:
      - xform/ui2/uí/ 
```
![image](https://user-images.githubusercontent.com/6355592/49938191-19147500-ff14-11e8-8a46-213ecb29b3d3.png)
